### ISSUE TITLE
Call ip link set command failed

### ISSUE THREAD

**Issue by salmon** [projectcalico/calico-cni#105]
Hi, 
I use centos7 and kubernetes v1.3.0-alpha.5 and calico-cni v1.3.1.
But it alway fail at execute command like "ip link set tmp0861f04c2c1 netns 0865a7462c1311e6b047525400b95203"

```
uname -a
Linux vagrant2 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linu
hyperkube --version
Kubernetes v1.3.0-alpha.5
```
My Calico Version:
```
/opt/cni/bin/calico --version
{
  "Commit": "f2e2cf774646b443f2f9f499e7650b444e0e7bfa", 
  "Version": "v1.3.1", 
  "Branch": "master"
}
```
Calico Cni Config
```
/etc/cni/net.d/10-calico.conf 
{
  "name": "calico-k8s-net",
  "type": "calico",
  "etcd_endpoints": "http://172.18.8.100:2379,http://172.18.8.101:2379,http://172.18.8.102:2379",
  "log_level": "debug",
  "log_level_stderr": "debug",
  "ipam": {
    "type": "calico-ipam"
  }
}
```
Log:
```
2016-06-07 02:18:13,799 6520 [kube-system/container-terminal-0f56z] INFO Assigned IPv4: 192.168.109.189/32, IPv6: None
2016-06-07 02:18:13,799 6520 [kube-system/container-terminal-0f56z] DEBUG Returning response: {'ip4': {'ip': '192.168.109.189/32'}}
2016-06-07 02:18:13,799 6520 [kube-system/container-terminal-0f56z] DEBUG IPAM response (rc=0): {"ip4": {"ip": "192.168.109.189/32"}}
2016-06-07 02:18:13,800 6520 [kube-system/container-terminal-0f56z] INFO IPAM plugin assigned IPv4 address: 192.168.109.189/32
2016-06-07 02:18:13,800 6520 [kube-system/container-terminal-0f56z] DEBUG Creating Calico endpoint with workload_id=kube-system.container-terminal-0f56z
2016-06-07 02:18:13,801 6520 [kube-system/container-terminal-0f56z] INFO Created Calico endpoint with IP address(es) [IPNetwork('192.168.109.189/32')]
2016-06-07 02:18:13,802 6520 [kube-system/container-terminal-0f56z] DEBUG Provisioning Calico veth interface
2016-06-07 02:18:13,802 6520 [kube-system/container-terminal-0f56z] DEBUG netns path: /proc/6433/ns/net
2016-06-07 02:18:13,802 6520 [kube-system/container-terminal-0f56z] DEBUG Creating veth cali0861f04c2c1 in temp_ns: tmp0861f04c2c1
2016-06-07 02:18:13,826 6520 [kube-system/container-terminal-0f56z] DEBUG Creating link between namespace 0865a7462c1311e6b047525400b95203 and PID /proc/6433/ns/net
2016-06-07 02:18:13,826 6520 [kube-system/container-terminal-0f56z] DEBUG Moving temp interface tmp0861f04c2c1 into ns 0865a7462c1311e6b047525400b95203.
2016-06-07 02:18:13,832 6520 [kube-system/container-terminal-0f56z] ERROR Failed to provision veth interface for endpoint cali0861f04c2c1
Traceback (most recent call last):
  File "<string>", line 629, in _provision_veth
  File "pycalico/datastore_datatypes.py", line 346, in provision_veth
  File "pycalico/netns.py", line 166, in move_veth_into_ns
  File "site-packages/subprocess32.py", line 638, in check_output
CalledProcessError: Command '['ip', 'link', 'set', 'tmp0861f04c2c1', 'netns', '0865a7462c1311e6b047525400b95203']' returned non-zero exit status 255
2016-06-07 02:18:13,832 6520 [kube-system/container-terminal-0f56z] INFO Removing Calico workload 'kube-system.container-terminal-0f56z'
2016-06-07 02:18:13,838 6520 [kube-system/container-terminal-0f56z] DEBUG Could not find workload with workload ID kube-system.container-terminal-0f56z.
2016-06-07 02:18:13,847 6520 [kube-system/container-terminal-0f56z] WARNING Could not find workload with container ID a599616773aa953fb673e7c17c0f9e13e4d908826069744959aabac6936ae514.
2016-06-07 02:18:13,847 6520 [kube-system/container-terminal-0f56z] INFO Releasing IP address
2016-06-07 02:18:13,847 6520 [kube-system/container-terminal-0f56z] INFO Using Calico IPAM
2016-06-07 02:18:13,851 6520 [kube-system/container-terminal-0f56z] DEBUG Parsing CNI_ARGS: IgnoreUnknown=1;IgnoreUnknown=1
2016-06-07 02:18:13,851 6520 [kube-system/container-terminal-0f56z] DEBUG       CNI_ARG: IgnoreUnknown=1
2016-06-07 02:18:13,851 6520 [kube-system/container-terminal-0f56z] DEBUG       CNI_ARG: IgnoreUnknown=1
2016-06-07 02:18:13,851 6520 [kube-system/container-terminal-0f56z] DEBUG Parsed CNI_ARGS: {'IGNOREUNKNOWN': '1'}
2016-06-07 02:18:13,851 6520 [kube-system/container-terminal-0f56z] DEBUG Environment: {
  "LANG": "en_US.UTF-8",
  "CNI_IFNAME": "eth0",
  "CNI_NETNS": "/proc/6433/ns/net",
  "CNI_PATH": "/opt/cni/bin:/opt/calico/bin",
  "CNI_ARGS": "IgnoreUnknown=1;IgnoreUnknown=1",
  "CNI_COMMAND": "DEL",
  "ETCD_ENDPOINTS": "http://172.18.8.100:2379,http://172.18.8.101:2379,http://172.18.8.102:2379",
  "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin",
  "CNI_CONTAINERID": "a599616773aa953fb673e7c17c0f9e13e4d908826069744959aabac6936ae514",
  "LD_LIBRARY_PATH": "/tmp/_MEIIm5HGt"
}
2016-06-07 02:18:13,851 6520 [kube-system/container-terminal-0f56z] INFO Releasing addresses on workload: a599616773aa953fb673e7c17c0f9e13e4d908826069744959aabac6936ae514
2016-06-07 02:18:13,887 6520 [kube-system/container-terminal-0f56z] DEBUG IPAM response (rc=0): None
2016-06-07 02:18:13,887 6520 [kube-system/container-terminal-0f56z] ERROR CNI Error:
{
  "msg": "",
  "cniVersion": "0.1.0",
  "code": 100,
  "details": null
}
Traceback (most recent call last):
  File "<string>", line 629, in _provision_veth
  File "pycalico/datastore_datatypes.py", line 346, in provision_veth
  File "pycalico/netns.py", line 166, in move_veth_into_ns
  File "site-packages/subprocess32.py", line 638, in check_output
CalledProcessError: Command '['ip', 'link', 'set', 'tmp0861f04c2c1', 'netns', '0865a7462c1311e6b047525400b95203']' returned non-zero exit status 255
2016-06-07 02:18:13,887 6520 [kube-system/container-terminal-0f56z] INFO Calico CNI execution complete, rc=100
```
Thanks.

**Comment by fasaxc** [comment]
@salmon How are you running the kubelet, could it be running with restricted permissions, say in a container or something?

**Comment by salmon** [comment]
Thank for your reply @fasaxc 
calico has right permissions
I run kubelet with systemd not in container, here is my systemd config file:
```
[Unit]
Description=Kubernetes Kubelet
After=docker.service
Requires=docker.service

[Service]
ExecStart=/opt/kubernetes/bin/hyperkube kubelet \
    --logtostderr=false \
    --v=4 \
    --address=0.0.0.0 \
    --cluster_dns=10.10.10.10 \
    --cluster_domain=test.local \
    --port=10250 \
    --hostname_override=172.18.8.102 \
    --log_dir=/var/log/kubernetes \
    --config=/opt/kubernetes/manifests-multi \
    --kubeconfig=/srv/kubernetes/kubeconfig \
    --api_servers=http://172.18.8.102:8080 \
    --resolv-conf=/dev/null \
    --max-pods=200 \
    --network-plugin=cni \
    --network-plugin-dir=/etc/cni/net.d \
    --allow_privileged=true
Restart=always
RestartSec=15

[Install]
WantedBy=multi-user.target
```
Kubelet Log:
```
E0607 11:53:24.428472    2199 cni.go:167] Error adding network:
E0607 11:53:24.428516    2199 cni.go:118] Error while adding to cni network:
E0607 11:53:24.428550    2199 manager.go:1993] Failed to setup network for pod "kube-dns-dx2er_kube-system(fc8e333f-2c12-11e6-be13-525400b95203)" using network plugins "cni": ; Skipping pod
E0607 11:53:24.428472    2199 cni.go:167] Error adding network:
E0607 11:53:24.428704    2199 cni.go:118] Error while adding to cni network:
E0607 11:53:24.428730    2199 manager.go:1993] Failed to setup network for pod "container-terminal-0f56z_kube-system(fc8e3901-2c12-11e6-be13-525400b95203)" using network plugins "cni": ; Skipping pod
E0607 11:53:25.307727    2199 handler.go:278] unable to get fs usage from thin pool for device 3198: no cached value for usage of device 3198
E0607 11:53:25.588898    2199 handler.go:278] unable to get fs usage from thin pool for device 3218: no cached value for usage of device 3218
E0607 11:53:26.444259    2199 handler.go:278] unable to get fs usage from thin pool for device 3214: no cached value for usage of device 3214
E0607 11:53:27.644742    2199 handler.go:278] unable to get fs usage from thin pool for device 3208: no cached value for usage of device 3208
E0607 11:53:28.581139    2199 pod_workers.go:183] Error syncing pod fc8e333f-2c12-11e6-be13-525400b95203, skipping: failed to "SetupNetwork" for "kube-dns-dx2er_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-dx2er_kube-system(fc8e333f-2c12-11e6-be13-525400b95203)\" using network plugins \"cni\": ; Skipping pod"
E0607 11:53:28.753379    2199 handler.go:278] unable to get fs usage from thin pool for device 3216: no cached value for usage of device 3216
E0607 11:53:29.373611    2199 handler.go:278] unable to get fs usage from thin pool for device 3240: no cached value for usage of device 3240
E0607 11:53:32.627742    2199 handler.go:278] unable to get fs usage from thin pool for device 3206: no cached value for usage of device 3206
E0607 11:53:30.908397    2199 manager.go:345] NetworkPlugin cni failed on the status hook for pod 'container-log-tx7ur' - invalid CIDR address: Device "eth0" does not exist.
E0607 11:53:33.700888    2199 handler.go:278] unable to get fs usage from thin pool for device 3196: no cached value for usage of device 3196
E0607 11:53:34.269030    2199 handler.go:278] unable to get fs usage from thin pool for device 3244: no cached value for usage of device 3244
E0607 11:53:34.269960    2199 handler.go:278] unable to get fs usage from thin pool for device 3232: no cached value for usage of device 3232
E0607 11:53:34.433540    2199 handler.go:278] unable to get fs usage from thin pool for device 3248: no cached value for usage of device 3248
E0607 11:53:34.449318    2199 handler.go:278] unable to get fs usage from thin pool for device 3228: no cached value for usage of device 3228
```

**Comment by salmon** [comment]
I found out the reason. I didn't close the selinux. After I disable selinux, calico can run good.
```
type=AVC msg=audit(1465358010.352:5986): avc:  denied  { read } for  pid=4901 comm="ip" name="netns" dev="tmpfs" ino=27968 scontext=system_u:system_r:ifconfig_t:s0 tcontext=system_u:object_r:init_var_run_t:s0 tclass=dir
```
