### ISSUE TITLE
CNI plugin fails to respect IP address type of subject alternative name in apiserver's TLS certificate

### ISSUE THREAD

**Issue by MikeSpreitzer** [projectcalico/calico-cni#120]
I found this complaint in my CNI plugin's log:
```
2016-07-10 00:02:47,157 9293 [kube-system/kube-dns-v9-eei3v] DEBUG Querying Kubernetes API for Pod: https://100.127.0.2:443/api/v1/namespaces/kube-system/pods/kube-dns-v9-eei3v
2016-07-10 00:02:47,157 9293 [kube-system/kube-dns-v9-eei3v] DEBUG Using client certificate for Query API. cert: /etc/kubernetes/ssl/worker.pem, key: /etc/kubernetes/ssl/worker-key.pem
2016-07-10 00:02:47,180 9293 [kube-system/kube-dns-v9-eei3v] ERROR Exception hitting Kubernetes API
Traceback (most recent call last):
  File "calico_cni/policy_drivers.py", line 293, in _get_api_pod
  File "site-packages/requests/sessions.py", line 480, in get
  File "site-packages/requests/sessions.py", line 468, in request
  File "site-packages/requests/sessions.py", line 576, in send
  File "site-packages/requests/adapters.py", line 447, in send
SSLError: hostname '100.127.0.2' doesn't match either of 'kubernetes', 'kubernetes.default'
```
But here is the certificate that the apiserver is offering:
```
$ openssl x509 -noout -text -in apiserver.pem
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 11165521009840230133 (0x9af3e63373b00ef5)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=kube-ca
        Validity
            Not Before: Jun  6 17:16:10 2016 GMT
            Not After : Jun  6 17:16:10 2017 GMT
        Subject: CN=kube-apiserver
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    <snip/>
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Alternative Name: 
                DNS:kubernetes, DNS:kubernetes.default, IP Address:10.100.0.1, IP Address:100.127.0.2
    Signature Algorithm: sha256WithRSAEncryption
         <snip/>
```

**Comment by MikeSpreitzer** [comment]
And, just to prove I am not crazy:
```
/etc/kubernetes/ssl$ sudo openssl s_client -connect 100.127.0.2:443 -cert worker.pem -key worker-key.pem -CAfile ca.pem 
CONNECTED(00000003)
depth=1 CN = kube-ca
verify return:1
depth=0 CN = kube-apiserver
verify return:1
---
Certificate chain
 0 s:/CN=kube-apiserver
   i:/CN=kube-ca
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIC/zCCAeegAwIBAgIJAJrz5jNzsA71MA0GCSqGSIb3DQEBCwUAMBIxEDAOBgNV
BAMMB2t1YmUtY2EwHhcNMTYwNjA2MTcxNjEwWhcNMTcwNjA2MTcxNjEwWjAZMRcw
FQYDVQQDEw5rdWJlLWFwaXNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAK1cZX/6jNyzl+/PYt+HRb3+BsX72+u70fHVGb8jE9tu1n4uZronkSMl
0fNye8XIuNa6N/Vf19HcdKEmIAYcQZwc1HysgcMIj59hJovxmqNRDkil2Ff/Orfx
jM9nV9SHfptyweRurO5Lfv8VSjLQ+qxY/2jNRzs0Z8p22iXEGBsKAuXI6QuMqbm2
v6NzV/V0VwQRYB4AUzhm3DRn4u7J52v4m5Ef7lSdaZtcg784aZm3rLFrWE/GJSBP
WKza7ZVQ7k7Pwpw54O0WT7SS/qydH6I770TAjxlp6MKNELlEF88STN8EIhhZV38F
OZgAlcsdKPo2ggxCUfMze6tSq3uxl90CAwEAAaNRME8wCQYDVR0TBAIwADALBgNV
HQ8EBAMCBeAwNQYDVR0RBC4wLIIKa3ViZXJuZXRlc4ISa3ViZXJuZXRlcy5kZWZh
dWx0hwQKZAABhwRkfwACMA0GCSqGSIb3DQEBCwUAA4IBAQBAl5jBNQxftek2Ndum
HphZh7alnTUn7O7WJCqRa4VxgxDkPdIYIb2FYp4yPlVA6kZpWpov6OeAypq3hi2d
gJfs04nbEOjJo5NfWoITgRu5P+ttIDJJpjw2/CIgA1dmEKXMWuBBPPrlbIV1OSbE
K36+GuyUP7ZA4QvisqT2suxikzPUWWUq//1BLusjopcTtYL9dgrmB6XNg0JP0qkI
743QxUYwETrSDhokxurKaKJvCPYq52EFtcyvcN23iRGtBzv+HPc/idIWSXclWyYV
LMdgW+gtzFyGu1L//vIpC4lg6wHrXjhbFZeUlJ4sjvTulYPErWQpDTKwhGTo5uRS
oZce
-----END CERTIFICATE-----
subject=/CN=kube-apiserver
issuer=/CN=kube-ca
---
Acceptable client certificate CA names
/CN=kube-ca
Client Certificate Types: RSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA1:ECDSA+SHA1
Peer signing digest: SHA384
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2927 bytes and written 2210 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
...
```

**Comment by MikeSpreitzer** [comment]
Or, a little more succinctly:
```
/etc/kubernetes/ssl$ sudo curl --cacert ca.pem --cert worker.pem --key worker-key.pem https://100.127.0.2/version
{
  "major": "1",
  "minor": "3",
  "gitVersion": "v1.3.0",
  "gitCommit": "283137936a498aed572ee22af6774b6fb6e9fd94",
  "gitTreeState": "clean",
  "buildDate": "2016-07-01T19:19:19Z",
  "goVersion": "go1.6.2",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Comment by MikeSpreitzer** [comment]
BTW: I am not familiar with the packaging technology used to build the CNI plugin, but it looks like it is not picking up the latest version of the `requests` package.

**Comment by caseydavenport** [comment]
I believe this is a urllib3 limitation where IP SANs are not respected.  See https://github.com/shazow/urllib3/pull/922

For now I think you'll need to use a DNS name.

**Comment by tomdee** [comment]
Shouild be fixed in Go version - just needs to be tested
