### ISSUE TITLE
Handle pods with no labels

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-cni#150]
Looks like we don't handle pods with no labels: https://github.com/projectcalico/calico-cni/blob/master/k8s/k8s.go#L188

```
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: Calico CNI checking for existing endpoint: <nil>
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: Calico CNI IPAM request count IPv4=1 IPv6=0
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: Calico CNI IPAM assigned addresses IPv4=[10.131.0.2] IPv6=[]
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: panic: assignment to entry in nil map
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: goroutine 1 [running, locked to thread]:
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: panic(0x1297be0, 0xc420242bc0)
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: github.com/projectcalico/calico-cni/k8s.getK8sLabels(0xc4201f0bc0, 0x1, 0x0, 0x0, 0x0, 0xc420359108, 0x7, 0xc4203590f0, 0x7, 0xc4203ce120, ...)
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: /go/src/github.com/projectcalico/calico-cni/k8s/k8s.go:188 +0x251
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: github.com/projectcalico/calico-cni/k8s.CmdAddK8s(0xc4203819d0, 0xc4203ec880, 0x12, 0xc4203c6948, 0x6, 0x0, 0x0, 0xc4203c6a20, 0xb, 0x0, ...)
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: /go/src/github.com/projectcalico/calico-cni/k8s/k8s.go:100 +0x95b
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: main.cmdAdd(0xc4203819d0, 0x3, 0x13fb17d)
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: /go/src/github.com/projectcalico/calico-cni/calico.go:96 +0x1712
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc4204b7de0, 0x14a4670, 0x14a4678, 0x0)
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: /go/src/github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:155 +0x303
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0x14a4670, 0x14a4678)
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: /go/src/github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:188 +0xd6
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: main.main()
Aug 19 17:16:19 ip-10-2-23-226.qa.xoom.com kubelet[15705]: /go/src/github.com/projectcalico/calico-cni/calico.go:300 +0x167
```

**Comment by caseydavenport** [comment]
CC @ae6rt
