### ISSUE TITLE
Error handling - pool end as example

### ISSUE THREAD

**Issue by jellonek** [projectcalico/calico-cni#188]
From kubectl describe:
```
Events:
  FirstSeen LastSeen    Count   From            SubobjectPath   Type        Reason      Message
  --------- --------    -----   ----            -------------   --------    ------      -------
  14m       14m     1   {default-scheduler }            Normal      Scheduled   Successfully assigned my-nginx-379829228-vjuop to node97
  14m       1s      416 {kubelet node97}            Warning     FailedSync  Error syncing pod, skipping: failed to "SetupNetwork" for "my-nginx-379829228-vjuop_default" with SetupNetworkError: "Failed to setup network for pod \"my-nginx-379829228-vjuop_default(295d7e9d-94bb-11e6-bcdf-f8bc1206f050)\" using network plugins \"cni\": netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input; Skipping pod"
```
In the same time syslog on this node noted:
```
Oct 17 06:25:13 node97 kubelet[19531]: ERROR: logging before flag.Parse: E1017 06:25:13.191945  102004 ipam.go:475] Error in auto assign: Block affinity (%!s(*string=0xc4202b1ad0)) does not match provided (node97)
Oct 17 06:25:13 node97 kubelet[19531]: ERROR: logging before flag.Parse: W1017 06:25:13.191981  102004 ipam.go:270] Failed to assign IPs in pool 10.233.64.0/18: Block affinity (%!s(*string=0xc4202b1ad0)) does not match provided (node97)
Oct 17 06:25:13 node97 kubelet[19531]: ERROR: logging before flag.Parse: E1017 06:25:13.194090  102004 ipam.go:465] Error getting block: resource does not exist: {{{fd80:24e2:f998:72d6:9314:8a74:cea7:2cc0 ffffffffffffffffffffffffffffffc0}}}
Oct 17 06:25:13 node97 kubelet[19531]: ERROR: logging before flag.Parse: W1017 06:25:13.194148  102004 ipam.go:270] Failed to assign IPs in pool fd80:24e2:f998:72d6::/64: resource does not exist: {{{fd80:24e2:f998:72d6:9314:8a74:cea7:2cc0 ffffffffffffffffffffffffffffffc0}}}
Oct 17 06:25:13 node97 kubelet[19531]: Calico CNI IPAM assigned addresses IPv4=[] IPv6=[]
Oct 17 06:25:13 node97 kubelet[19531]: panic: runtime error: index out of range
Oct 17 06:25:13 node97 kubelet[19531]: goroutine 1 [running]:
Oct 17 06:25:13 node97 kubelet[19531]: panic(0x9af180, 0xc42000a0b0)
Oct 17 06:25:13 node97 kubelet[19531]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Oct 17 06:25:13 node97 kubelet[19531]: main.cmdAdd(0xc42025fc70, 0x3, 0xa6e86a)
Oct 17 06:25:13 node97 kubelet[19531]: #011/go/src/github.com/projectcalico/calico-cni/ipam/calico-ipam.go:91 +0xe40
Oct 17 06:25:13 node97 kubelet[19531]: github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc42021bec0, 0xab62b0, 0xab62b8, 0xc4200a2058)
Oct 17 06:25:13 node97 kubelet[19531]: #011/go/src/github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:155 +0x303
Oct 17 06:25:13 node97 kubelet[19531]: github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0xab62b0, 0xab62b8)
Oct 17 06:25:13 node97 kubelet[19531]: #011/go/src/github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:188 +0xd6
Oct 17 06:25:13 node97 kubelet[19531]: main.main()
Oct 17 06:25:13 node97 kubelet[19531]: #011/go/src/github.com/projectcalico/calico-cni/ipam/calico-ipam.go:20 +0x39
Oct 17 06:25:13 node97 kubelet[19531]: E1017 06:25:13.198981   19561 cni.go:255] Error adding network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
Oct 17 06:25:13 node97 kubelet[19531]: E1017 06:25:13.198999   19561 cni.go:209] Error while adding to cni network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
```

Cause for this turned out to be no available addresses left in pool for ipv4 and (looks like) missing pool for ipv6. In both situation error seems to be propagated in wrong way, resulting in misleading info returned by kubelet (which expects correct json even on failure - maybe with different exit codes we could separate panic situation - exit code 2 - from other types of errors - but this is the question for k8s or cni issue tracker).

So looking cursorily - looks like there was no error returned in [calico-ipam.go#L84](https://github.com/projectcalico/calico-cni/blob/e180a66475ded867cb36a35268cc191a708e58be/ipam/calico-ipam.go#L84) but list of ipv4 addresses is empty and then accessing missing first element of array in [calico-ipam.go#L91](https://github.com/projectcalico/calico-cni/blob/e180a66475ded867cb36a35268cc191a708e58be/ipam/calico-ipam.go#L91) causes the panic.

Also maybe we should [recover](https://blog.golang.org/defer-panic-and-recover) to handle similar cases in a better way?

**Comment by mihgen** [comment]
I think that error has to be returned from calicoClient.IPAM().AutoAssign, because requests didn't actually succeed. 1 IP was requested, but none are allocated. So this is rather an issue for libcalico-go, I'll file a separate bug in that repo.

Data returned could be double-checked here too, of course.
