### ISSUE TITLE
Error while loading shared libraries: /tmp/_MEIIjB2Zs/libz.so.1

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-cni#34]
IPAM plugin fails to load shared library - most pods came up fine, but this one didn't.  Saving diags here for further investigation.

Seen on CoreOS Stable 835.9.0, Kubernetes v1.1.3.  Using master build of calico-cni at commit 69a95dbb8888d5d1eb6467543d98165b4ecf20b2

```
2016-01-13 00:39:54,291 6254 [default/busybox-53bvw] DEBUG Loaded network config:
{
  "log_level": "debug",
  "name": "calico-k8s-network",
  "policy": {
    "k8s_auth_token": "...",
    "type": "k8s-annotations"
  },
  "ipam": {
    "type": "calico-ipam"
  },
  "type": "calico",
  "etcd_authority": "172.24.114.18:6666"
}
2016-01-13 00:39:54,292 6254 [default/busybox-53bvw] DEBUG Using ETCD_AUTHORITY=172.24.114.18:6666
2016-01-13 00:39:54,295 6254 [default/busybox-53bvw] DEBUG Loaded environment:
{
  "CNI_IFNAME": "eth0",
  "CNI_NETNS": "/proc/6224/ns/net",
  "CNI_PATH": "/opt/cni/bin:/opt/calico/bin",
  "CNI_ARGS": "K8S_POD_NAMESPACE=default;K8S_POD_NAME=busybox-53bvw;K8S_POD_INFRA_CONTAINER_ID=fff5d1053708933ed0148a6f69d7af32abe0d7313b66239d5346f6ac2d113bf1",
  "PYTHONPATH": "/tmp/_MEIVpyB0W",
  "DEFAULT_IPV4": "172.24.114.31",
  "CNI_COMMAND": "ADD",
  "LO_IPV4": "127.0.0.1",
  "ENP0S3_IPV4": "172.24.114.31",
  "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "CNI_CONTAINERID": "fff5d1053708933ed0148a6f69d7af32abe0d7313b66239d5346f6ac2d113bf1",
  "LD_LIBRARY_PATH": "/tmp/_MEIVpyB0W",
  "ETCD_AUTHORITY": "172.24.114.18:6666"
}
2016-01-13 00:39:54,296 6254 [default/busybox-53bvw] DEBUG Parsing CNI_ARGS: K8S_POD_NAMESPACE=default;K8S_POD_NAME=busybox-53bvw;K8S_POD_INFRA_CONTAINER_ID=fff5d1053708933ed0148a6f69d7af32abe0d7313b66239d5346f6ac2d113bf1
2016-01-13 00:39:54,296 6254 [default/busybox-53bvw] DEBUG      CNI_ARG: K8S_POD_NAMESPACE=default
2016-01-13 00:39:54,297 6254 [default/busybox-53bvw] DEBUG      CNI_ARG: K8S_POD_NAME=busybox-53bvw
2016-01-13 00:39:54,297 6254 [default/busybox-53bvw] DEBUG      CNI_ARG: K8S_POD_INFRA_CONTAINER_ID=fff5d1053708933ed0148a6f69d7af32abe0d7313b66239d5346f6ac2d113bf1
2016-01-13 00:39:54,297 6254 [default/busybox-53bvw] DEBUG Parsed CNI_ARGS: {'K8S_POD_NAME': 'busybox-53bvw', 'K8S_POD_NAMESPACE': 'default', 'K8S_POD_INFRA_CONTAINER_ID': 'fff5d1053708933ed0148a6f69d7af32abe0d7313b66239d5346f6ac2d113bf1'}
2016-01-13 00:39:54,298 6254 [default/busybox-53bvw] DEBUG Using Kubernetes Annotation Policy Driver
2016-01-13 00:39:54,299 6254 [default/busybox-53bvw] DEBUG Using Kubernetes + Docker container engine
2016-01-13 00:39:54,322 6254 [default/busybox-53bvw] INFO Starting Calico CNI plugin execution
2016-01-13 00:39:54,344 6254 [default/busybox-53bvw] INFO Configuring network 'calico-k8s-network' for container: fff5d1053708933ed0148a6f69d7af32abe0d7313b66239d5346f6ac2d113bf1
2016-01-13 00:39:54,359 6254 [default/busybox-53bvw] DEBUG Checking for existing Calico endpoint
2016-01-13 00:39:54,359 6254 [default/busybox-53bvw] DEBUG Looking for endpoint that matches container ID fff5d1053708933ed0148a6f69d7af32abe0d7313b66239d5346f6ac2d113bf1
2016-01-13 00:39:54,365 6254 [default/busybox-53bvw] DEBUG No endpoint found matching ID fff5d1053708933ed0148a6f69d7af32abe0d7313b66239d5346f6ac2d113bf1
2016-01-13 00:39:54,372 6254 [default/busybox-53bvw] INFO Configuring a new Endpoint for container
2016-01-13 00:39:54,379 6254 [default/busybox-53bvw] DEBUG Assigning IP address
2016-01-13 00:39:54,380 6254 [default/busybox-53bvw] DEBUG Looking for plugin calico-ipam in path /opt/cni/bin
2016-01-13 00:39:54,381 6254 [default/busybox-53bvw] DEBUG Found plugin calico-ipam in path /opt/cni/bin
2016-01-13 00:39:54,381 6254 [default/busybox-53bvw] INFO Using IPAM plugin at: /opt/cni/bin/calico-ipam
2016-01-13 00:39:54,381 6254 [default/busybox-53bvw] DEBUG Passing in environment to IPAM plugin:
{
  "CNI_IFNAME": "eth0",
  "CNI_NETNS": "/proc/6224/ns/net",
  "CNI_PATH": "/opt/cni/bin:/opt/calico/bin",
  "CNI_ARGS": "K8S_POD_NAMESPACE=default;K8S_POD_NAME=busybox-53bvw;K8S_POD_INFRA_CONTAINER_ID=fff5d1053708933ed0148a6f69d7af32abe0d7313b66239d5346f6ac2d113bf1",
  "PYTHONPATH": "/tmp/_MEIVpyB0W",
  "DEFAULT_IPV4": "172.24.114.31",
  "CNI_COMMAND": "ADD",
  "LO_IPV4": "127.0.0.1",
  "ENP0S3_IPV4": "172.24.114.31",
  "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "CNI_CONTAINERID": "fff5d1053708933ed0148a6f69d7af32abe0d7313b66239d5346f6ac2d113bf1",
  "LD_LIBRARY_PATH": "/tmp/_MEIVpyB0W",
  "ETCD_AUTHORITY": "172.24.114.18:6666"
}
2016-01-13 00:39:55,034 6254 [default/busybox-53bvw] DEBUG IPAM plugin return code: 127
2016-01-13 00:39:55,034 6254 [default/busybox-53bvw] DEBUG IPAM plugin output:
stdout:

stderr:
/opt/cni/bin/calico-ipam: error while loading shared libraries: /tmp/_MEIIjB2Zs/libz.so.1: file too short

2016-01-13 00:39:55,035 6254 [default/busybox-53bvw] ERROR Failed to parse IPAM response, exiting
Traceback (most recent call last):
  File "<string>", line 309, in _assign_ips
  File "/code/build/calico/out00-PYZ.pyz/json", line 326, in loads
  File "/code/build/calico/out00-PYZ.pyz/json.decoder", line 365, in decode
  File "/code/build/calico/out00-PYZ.pyz/json.decoder", line 383, in raw_decode
ValueError: No JSON object could be decoded
2016-01-13 00:39:55,038 6254 [default/busybox-53bvw] ERROR CNI Error:
{
  "msg": "Failed to parse IPAM response, exiting",
  "cniVersion": "0.1.0",
  "code": 100,
  "details": null
}
2016-01-13 00:39:55,041 6254 [default/busybox-53bvw] INFO Calico CNI execution complete, rc=100
```

**Comment by caseydavenport** [comment]
Reboot seemed to fix it, closing for now as not reproducible.
