### ISSUE TITLE
Timeout when deleting veth interface.

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-cni#35]
Seen on CoreOS Stable 835.9.0, Kubernetes v1.1.3. Using master build of calico-cni at commit 69a95db

During a CNI DEL, timed out while attempting to remove veth.  Unsure what caused the timeout (wasn't under high load), but we should probably be handling this case so that we properly tear down as much as we can during DEL.

```
2016-01-13 00:33:42,286 32538 [default/busybox-m218t] DEBUG Looking for endpoint that matches container ID 053ed3ef931e6da6999482bd2bf4b181ba80df6623da237ca1c94814c22fae77
2016-01-13 00:33:42,790 32538 [default/busybox-m218t] INFO Removing veth for endpoint: cali17d364f0b98
2016-01-13 00:33:58,300 32538 [default/busybox-m218t] ERROR Unhandled Exception killed plugin
Traceback (most recent call last):
  File "<string>", line 126, in execute
  File "<string>", line 153, in _execute
  File "<string>", line 285, in delete
  File "<string>", line 483, in _remove_veth
  File "/code/build/calico/out00-PYZ.pyz/pycalico.netns", line 111, in remove_veth
  File "/code/build/calico/out00-PYZ.pyz/subprocess32", line 635, in check_output
TimeoutExpired: Command '['ip', 'link', 'del', u'cali17d364f0b98']' timed out after 5 seconds
2016-01-13 00:34:06,156 32538 [default/busybox-m218t] ERROR CNI Error:
{
  "msg": "Unhandled Exception killed plugin",
  "cniVersion": "0.1.0",
  "code": 101,
  "details": null
}
2016-01-13 00:34:06,225 32538 [default/busybox-m218t] INFO Calico CNI execution complete, rc=101
```

**Comment by caseydavenport** [comment]
Closing this as not reproducible - I haven't seen this since, and it was on an unreleased commit.
