### ISSUE TITLE
Cannot assign IP to a container, with "BGP configuration for host node1 not found" error

### ISSUE THREAD

**Issue by inercia** [projectcalico/calico-cni#89]
Hi there,

I cannot get Calico assign an IP to my nodes in Kubernetes cluster. All I see is this kind of errors in the logs:

```
2016-04-15 16:44:21,008 25670 [kube-system/kube-dns-v11-59clu] INFO Configuring network 'calico-k8s-network' for container: c4e0d16f455a7729c8062a3deb00af51552405c4567f850ece2ba68c5a93ce12
2016-04-15 16:44:21,008 25670 [kube-system/kube-dns-v11-59clu] DEBUG Checking for existing Calico endpoint
2016-04-15 16:44:21,008 25670 [kube-system/kube-dns-v11-59clu] DEBUG Looking for endpoint that matches workload ID kube-system.kube-dns-v11-59clu
2016-04-15 16:44:21,009 25670 [kube-system/kube-dns-v11-59clu] DEBUG No endpoint found matching workload ID kube-system.kube-dns-v11-59clu
2016-04-15 16:44:21,010 25670 [kube-system/kube-dns-v11-59clu] DEBUG No endpoint found matching container ID c4e0d16f455a7729c8062a3deb00af51552405c4567f850ece2ba68c5a93ce12
2016-04-15 16:44:21,010 25670 [kube-system/kube-dns-v11-59clu] INFO No endpoint exists for workload - creating
2016-04-15 16:44:21,010 25670 [kube-system/kube-dns-v11-59clu] INFO Configuring a new Endpoint
2016-04-15 16:44:21,011 25670 [kube-system/kube-dns-v11-59clu] DEBUG Assigning IP address
2016-04-15 16:44:21,011 25670 [kube-system/kube-dns-v11-59clu] INFO Using Calico IPAM
2016-04-15 16:44:21,011 25670 [kube-system/kube-dns-v11-59clu] DEBUG Parsing CNI_ARGS: IgnoreUnknown=1;IgnoreUnknown=1
2016-04-15 16:44:21,011 25670 [kube-system/kube-dns-v11-59clu] DEBUG    CNI_ARG: IgnoreUnknown=1
2016-04-15 16:44:21,011 25670 [kube-system/kube-dns-v11-59clu] DEBUG    CNI_ARG: IgnoreUnknown=1
2016-04-15 16:44:21,011 25670 [kube-system/kube-dns-v11-59clu] DEBUG Parsed CNI_ARGS: {'IGNOREUNKNOWN': '1'}
2016-04-15 16:44:21,011 25670 [kube-system/kube-dns-v11-59clu] DEBUG Environment: {
  "CNI_IFNAME": "eth0", 
  "CNI_NETNS": "/proc/25648/ns/net", 
  "CNI_PATH": "/opt/cni/bin:/opt/calico/bin", 
  "KUBE_LOGTOSTDERR": "--logtostderr=true", 
  "CNI_ARGS": "IgnoreUnknown=1;IgnoreUnknown=1", 
  "KUBELET_API_SERVER": "--api-servers=http://172.25.128.10:8080", 
  "KUBELET_PORT": "--port=10250", 
  "LC_CTYPE": "en_US.UTF-8", 
  "KUBE_ENABLE_DAEMONSETS": "true", 
  "CNI_COMMAND": "ADD", 
  "KUBE_ALLOW_PRIV": "--allow-privileged=true", 
  "KUBE_LOG_LEVEL": "--v=2", 
  "KUBELET_ADDRESS": "--address=0.0.0.0", 
  "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", 
  "KUBELET_ARGS": "--cluster-dns=172.21.0.2     --cluster-domain=cluster.local  --network-plugin=cni --network-plugin-dir=/etc/cni/net.d ", 
  "CNI_CONTAINERID": "c4e0d16f455a7729c8062a3deb00af51552405c4567f850ece2ba68c5a93ce12", 
  "LD_LIBRARY_PATH": "/tmp/_MEIYiS8Me", 
  "ETCD_AUTHORITY": "172.25.128.10:2379", 
  "KUBE_MASTER": "--master=http://172.25.128.10:8080"
}
2016-04-15 16:44:21,011 25670 [kube-system/kube-dns-v11-59clu] INFO Assigning address to workload: c4e0d16f455a7729c8062a3deb00af51552405c4567f850ece2ba68c5a93ce12
2016-04-15 16:44:21,011 25670 [kube-system/kube-dns-v11-59clu] INFO Assigning 1 IPv4 and 0 IPv6 addresses
2016-04-15 16:44:21,064 25669 [kube-system/kubernetes-dashboard-v1.0.0-ck7j1] DEBUG Allocated ip4s: [IPAddress('172.20.0.62')], ip6s: []
2016-04-15 16:44:21,065 25669 [kube-system/kubernetes-dashboard-v1.0.0-ck7j1] INFO Assigned IPv4: 172.20.0.62/32, IPv6: None
2016-04-15 16:44:21,065 25669 [kube-system/kubernetes-dashboard-v1.0.0-ck7j1] DEBUG Returning response: {'ip4': {'ip': '172.20.0.62/32'}}
2016-04-15 16:44:21,065 25669 [kube-system/kubernetes-dashboard-v1.0.0-ck7j1] DEBUG IPAM response (rc=0): {"ip4": {"ip": "172.20.0.62/32"}}
2016-04-15 16:44:21,065 25669 [kube-system/kubernetes-dashboard-v1.0.0-ck7j1] INFO IPAM plugin assigned IPv4 address: 172.20.0.62/32
2016-04-15 16:44:21,065 25669 [kube-system/kubernetes-dashboard-v1.0.0-ck7j1] DEBUG Creating Calico endpoint with workload_id=kube-system.kubernetes-dashboard-v1.0.0-ck7j1
2016-04-15 16:44:21,067 25669 [kube-system/kubernetes-dashboard-v1.0.0-ck7j1] ERROR Failed to create Calico endpoint.
Traceback (most recent call last):
  File "<string>", line 498, in _create_endpoint
  File "site-packages/pycalico/datastore.py", line 128, in wrapped
  File "site-packages/pycalico/datastore.py", line 1284, in create_endpoint
  File "site-packages/pycalico/datastore.py", line 128, in wrapped
  File "site-packages/pycalico/datastore.py", line 1331, in get_default_next_hops
KeyError: 'BGP configuration for host node1 not found.
```

Any suggestion?

Cheers

**Comment by inercia** [comment]
Oh, it seems it is solved after some time.... I guess it was waiting for something, right?

**Comment by caseydavenport** [comment]
Hi @inercia - the BGP configuration that was missing gets configured by the `calico/node` container.  If the `calico/node` container hasn't started yet at least once on that node, creating pods via CNI will fail.

I believe there is some work in progress to eliminate this ordering requirement, but for now you should make sure that `calico/node` has run before scheduling pods to that node.

**Comment by inercia** [comment]
Perfect, thanks for you help @caseydavenport
